[project]
name = "reasearch-llama"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.5.0",
]

[tools.uv.dev-dependencies]
test = ["pytest"]
lint = ["ruff"]
